import type { Metadata } from 'next';
import { Inter, Manrope } from 'next/font/google';
import 'modern-normalize';
import './globals.css';
import TanStackProvider from '@/components/TanStackProvider/TanStackProvider';
import Header from '@/components/Header/Header';

const geistInter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

const geistManrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistInter.variable} ${geistManrope.variable}`}>
      <body>
        <TanStackProvider>
          <Header />
          <div className='container'>{children}</div>
        </TanStackProvider>
      </body>
    </html>
  );
}
